AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template Practice

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:
  YasmineCFBucket:
    Type: AWS::S3::Bucket
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: YasmineFirstQueue
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref LatestAmiId
      SecurityGroupIds:
        - !Ref SGOne
  MyElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Instances: [!Ref MyInstance]
      AvailabilityZones:
        - "eu-west-2a"
      Listeners:
        - LoadBalancerPort: '80'
          InstancePort: '80'
          Protocol: HTTP
      SecurityGroups:
        - !Ref SGTwo
  SGOne:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-081c6760
      GroupDescription: Security group for EC2 instance.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          SourceSecurityGroupId: !Ref SGTwo
  SGTwo:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-081c6760
      GroupDescription: Security group for load balancer.

Outputs:
  MyElasticLoadBalancerDNSName:
    Value: !GetAtt MyElasticLoadBalancer.DNSName
    Description: Load Balancer DNS name